spring:
  application:
    name: GestionInvdeHerrMicroservices
  cloud:
    config:
      enabled: true
      uri: http://localhost:8081
  datasource:
    url: jdbc:postgres://localhost:5432/Gestiondeclientes
    username: postgres
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
