apiVersion: v1
kind: Secret
metadata:
  name: keycloak-client-secrets
type: Opaque
data:
  # Los valores deben estar en base64
  # echo -n "sisgr-backend" | base64
  client-id: c2lzZ3ItYmFja2VuZA==
  # echo -n "V8NoGAL7RPlrjfnN4KMv4c0sczK3BYKf" | base64
  client-secret: VjhOb0dBTDdSUGxyamZuTjRLTXY0YzBzY3pLM0JZS2Y=